/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OASPlash.Core.Client.FileParameter;
using OpenAPIDateConverter = OASPlash.Core.Client.OpenAPIDateConverter;

namespace OASPlash.Core.Model
{
    /// <summary>
    /// Defines Orientation
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Orientation
    {
        /// <summary>
        /// Enum Landscape for value: landscape
        /// </summary>
        [EnumMember(Value = "landscape")]
        Landscape = 1,

        /// <summary>
        /// Enum Portrait for value: portrait
        /// </summary>
        [EnumMember(Value = "portrait")]
        Portrait = 2,

        /// <summary>
        /// Enum Squarish for value: squarish
        /// </summary>
        [EnumMember(Value = "squarish")]
        Squarish = 3

    }

}
