/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OASPlash.Core.Client.FileParameter;
using OpenAPIDateConverter = OASPlash.Core.Client.OpenAPIDateConverter;

namespace OASPlash.Core.Model
{
    /// <summary>
    /// PhotoStatisticsDownloads
    /// </summary>
    [DataContract(Name = "PhotoStatistics_downloads")]
    public partial class PhotoStatisticsDownloads : IEquatable<PhotoStatisticsDownloads>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhotoStatisticsDownloads" /> class.
        /// </summary>
        /// <param name="total">total.</param>
        /// <param name="historical">historical.</param>
        public PhotoStatisticsDownloads(int total = default(int), PhotoHistoricalData historical = default(PhotoHistoricalData))
        {
            this.Total = total;
            this.Historical = historical;
        }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets Historical
        /// </summary>
        [DataMember(Name = "historical", EmitDefaultValue = false)]
        public PhotoHistoricalData Historical { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhotoStatisticsDownloads {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Historical: ").Append(Historical).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PhotoStatisticsDownloads);
        }

        /// <summary>
        /// Returns true if PhotoStatisticsDownloads instances are equal
        /// </summary>
        /// <param name="input">Instance of PhotoStatisticsDownloads to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhotoStatisticsDownloads input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Total == input.Total ||
                    this.Total.Equals(input.Total)
                ) && 
                (
                    this.Historical == input.Historical ||
                    (this.Historical != null &&
                    this.Historical.Equals(input.Historical))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Total.GetHashCode();
                if (this.Historical != null)
                {
                    hashCode = (hashCode * 59) + this.Historical.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
