/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using OASPlash.Core.Client;
using OASPlash.Core.Model;

namespace OASPlash.Core.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICurrentUserApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get the user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CurrentUser</returns>
        CurrentUser GetCurrentUser();

        /// <summary>
        /// Get the user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CurrentUser</returns>
        ApiResponse<CurrentUser> GetCurrentUserWithHttpInfo();
        /// <summary>
        /// Update the current user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <returns>CurrentUser</returns>
        CurrentUser UpdateCurrentUser(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string));

        /// <summary>
        /// Update the current user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <returns>ApiResponse of CurrentUser</returns>
        ApiResponse<CurrentUser> UpdateCurrentUserWithHttpInfo(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICurrentUserApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get the user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CurrentUser</returns>
        System.Threading.Tasks.Task<CurrentUser> GetCurrentUserAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get the user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CurrentUser)</returns>
        System.Threading.Tasks.Task<ApiResponse<CurrentUser>> GetCurrentUserWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update the current user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CurrentUser</returns>
        System.Threading.Tasks.Task<CurrentUser> UpdateCurrentUserAsync(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update the current user&#39;s profile
        /// </summary>
        /// <remarks>
        /// Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CurrentUser)</returns>
        System.Threading.Tasks.Task<ApiResponse<CurrentUser>> UpdateCurrentUserWithHttpInfoAsync(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICurrentUserApi : ICurrentUserApiSync, ICurrentUserApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CurrentUserApi : IDisposable, ICurrentUserApi
    {
        private OASPlash.Core.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public CurrentUserApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public CurrentUserApi(string basePath)
        {
            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                new OASPlash.Core.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public CurrentUserApi(OASPlash.Core.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CurrentUserApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CurrentUserApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                new OASPlash.Core.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CurrentUserApi(HttpClient client, OASPlash.Core.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public CurrentUserApi(OASPlash.Core.Client.ISynchronousClient client, OASPlash.Core.Client.IAsynchronousClient asyncClient, OASPlash.Core.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public OASPlash.Core.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public OASPlash.Core.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public OASPlash.Core.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OASPlash.Core.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OASPlash.Core.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get the user&#39;s profile Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CurrentUser</returns>
        public CurrentUser GetCurrentUser()
        {
            OASPlash.Core.Client.ApiResponse<CurrentUser> localVarResponse = GetCurrentUserWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the user&#39;s profile Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CurrentUser</returns>
        public OASPlash.Core.Client.ApiResponse<CurrentUser> GetCurrentUserWithHttpInfo()
        {
            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (userAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CurrentUser>("/me", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCurrentUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the user&#39;s profile Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CurrentUser</returns>
        public async System.Threading.Tasks.Task<CurrentUser> GetCurrentUserAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OASPlash.Core.Client.ApiResponse<CurrentUser> localVarResponse = await GetCurrentUserWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the user&#39;s profile Note: To access a user&#39;s private data, the user is required to authorize the read_user scope. Without a Bearer token (i.e. using a Client-ID token) this request will return a 401 Unauthorized response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CurrentUser)</returns>
        public async System.Threading.Tasks.Task<OASPlash.Core.Client.ApiResponse<CurrentUser>> GetCurrentUserWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (userAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CurrentUser>("/me", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCurrentUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update the current user&#39;s profile Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <returns>CurrentUser</returns>
        public CurrentUser UpdateCurrentUser(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string))
        {
            OASPlash.Core.Client.ApiResponse<CurrentUser> localVarResponse = UpdateCurrentUserWithHttpInfo(bio, username, firstName, lastName, email, url, location, instagramUsername);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update the current user&#39;s profile Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <returns>ApiResponse of CurrentUser</returns>
        public OASPlash.Core.Client.ApiResponse<CurrentUser> UpdateCurrentUserWithHttpInfo(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string))
        {
            // verify the required parameter 'bio' is set
            if (bio == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'bio' when calling CurrentUserApi->UpdateCurrentUser");

            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (username != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "username", username));
            }
            if (firstName != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "first_name", firstName));
            }
            if (lastName != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "last_name", lastName));
            }
            if (email != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "email", email));
            }
            if (url != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "url", url));
            }
            if (location != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "location", location));
            }
            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "bio", bio));
            if (instagramUsername != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "instagram_username", instagramUsername));
            }

            // authentication (userAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<CurrentUser>("/me", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateCurrentUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update the current user&#39;s profile Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CurrentUser</returns>
        public async System.Threading.Tasks.Task<CurrentUser> UpdateCurrentUserAsync(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OASPlash.Core.Client.ApiResponse<CurrentUser> localVarResponse = await UpdateCurrentUserWithHttpInfoAsync(bio, username, firstName, lastName, email, url, location, instagramUsername, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update the current user&#39;s profile Note: This action requires the write_user scope. Without it, it will return a 403 Forbidden response. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bio">About/bio.</param>
        /// <param name="username">Username. (optional)</param>
        /// <param name="firstName">First name. (optional)</param>
        /// <param name="lastName">Last name. (optional)</param>
        /// <param name="email">Email. (optional)</param>
        /// <param name="url">Portfolio/personal URL. (optional)</param>
        /// <param name="location">Location. (optional)</param>
        /// <param name="instagramUsername">Instagram username. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CurrentUser)</returns>
        public async System.Threading.Tasks.Task<OASPlash.Core.Client.ApiResponse<CurrentUser>> UpdateCurrentUserWithHttpInfoAsync(string bio, string username = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string url = default(string), string location = default(string), string instagramUsername = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'bio' is set
            if (bio == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'bio' when calling CurrentUserApi->UpdateCurrentUser");


            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (username != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "username", username));
            }
            if (firstName != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "first_name", firstName));
            }
            if (lastName != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "last_name", lastName));
            }
            if (email != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "email", email));
            }
            if (url != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "url", url));
            }
            if (location != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "location", location));
            }
            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "bio", bio));
            if (instagramUsername != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "instagram_username", instagramUsername));
            }

            // authentication (userAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<CurrentUser>("/me", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateCurrentUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
