/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using OASPlash.Core.Client;
using OASPlash.Core.Model;

namespace OASPlash.Core.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISearchApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Search collections
        /// </summary>
        /// <remarks>
        /// Get a single page of collection results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>CollectionSearchResults</returns>
        CollectionSearchResults SearchCollections(string query, int? page = default(int?), int? perPage = default(int?));

        /// <summary>
        /// Search collections
        /// </summary>
        /// <remarks>
        /// Get a single page of collection results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>ApiResponse of CollectionSearchResults</returns>
        ApiResponse<CollectionSearchResults> SearchCollectionsWithHttpInfo(string query, int? page = default(int?), int? perPage = default(int?));
        /// <summary>
        /// Search photos
        /// </summary>
        /// <remarks>
        /// Get a single page of photo results for a query. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <returns>PhotoSearchResults</returns>
        PhotoSearchResults SearchPhotos(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?));

        /// <summary>
        /// Search photos
        /// </summary>
        /// <remarks>
        /// Get a single page of photo results for a query. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <returns>ApiResponse of PhotoSearchResults</returns>
        ApiResponse<PhotoSearchResults> SearchPhotosWithHttpInfo(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?));
        /// <summary>
        /// Search users
        /// </summary>
        /// <remarks>
        /// Get a single page of user results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>UserSearchResults</returns>
        UserSearchResults SearchUsers(string query, int? page = default(int?), int? perPage = default(int?));

        /// <summary>
        /// Search users
        /// </summary>
        /// <remarks>
        /// Get a single page of user results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>ApiResponse of UserSearchResults</returns>
        ApiResponse<UserSearchResults> SearchUsersWithHttpInfo(string query, int? page = default(int?), int? perPage = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISearchApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Search collections
        /// </summary>
        /// <remarks>
        /// Get a single page of collection results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CollectionSearchResults</returns>
        System.Threading.Tasks.Task<CollectionSearchResults> SearchCollectionsAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Search collections
        /// </summary>
        /// <remarks>
        /// Get a single page of collection results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CollectionSearchResults)</returns>
        System.Threading.Tasks.Task<ApiResponse<CollectionSearchResults>> SearchCollectionsWithHttpInfoAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Search photos
        /// </summary>
        /// <remarks>
        /// Get a single page of photo results for a query. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PhotoSearchResults</returns>
        System.Threading.Tasks.Task<PhotoSearchResults> SearchPhotosAsync(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Search photos
        /// </summary>
        /// <remarks>
        /// Get a single page of photo results for a query. 
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PhotoSearchResults)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhotoSearchResults>> SearchPhotosWithHttpInfoAsync(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Search users
        /// </summary>
        /// <remarks>
        /// Get a single page of user results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserSearchResults</returns>
        System.Threading.Tasks.Task<UserSearchResults> SearchUsersAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Search users
        /// </summary>
        /// <remarks>
        /// Get a single page of user results for a query.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserSearchResults)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserSearchResults>> SearchUsersWithHttpInfoAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISearchApi : ISearchApiSync, ISearchApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SearchApi : IDisposable, ISearchApi
    {
        private OASPlash.Core.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public SearchApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SearchApi(string basePath)
        {
            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                new OASPlash.Core.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SearchApi(OASPlash.Core.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SearchApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SearchApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                new OASPlash.Core.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SearchApi(HttpClient client, OASPlash.Core.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SearchApi(OASPlash.Core.Client.ISynchronousClient client, OASPlash.Core.Client.IAsynchronousClient asyncClient, OASPlash.Core.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public OASPlash.Core.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public OASPlash.Core.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public OASPlash.Core.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OASPlash.Core.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OASPlash.Core.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Search collections Get a single page of collection results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>CollectionSearchResults</returns>
        public CollectionSearchResults SearchCollections(string query, int? page = default(int?), int? perPage = default(int?))
        {
            OASPlash.Core.Client.ApiResponse<CollectionSearchResults> localVarResponse = SearchCollectionsWithHttpInfo(query, page, perPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search collections Get a single page of collection results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>ApiResponse of CollectionSearchResults</returns>
        public OASPlash.Core.Client.ApiResponse<CollectionSearchResults> SearchCollectionsWithHttpInfo(string query, int? page = default(int?), int? perPage = default(int?))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'query' when calling SearchApi->SearchCollections");

            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }

            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CollectionSearchResults>("/search/collections", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchCollections", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search collections Get a single page of collection results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CollectionSearchResults</returns>
        public async System.Threading.Tasks.Task<CollectionSearchResults> SearchCollectionsAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OASPlash.Core.Client.ApiResponse<CollectionSearchResults> localVarResponse = await SearchCollectionsWithHttpInfoAsync(query, page, perPage, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search collections Get a single page of collection results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CollectionSearchResults)</returns>
        public async System.Threading.Tasks.Task<OASPlash.Core.Client.ApiResponse<CollectionSearchResults>> SearchCollectionsWithHttpInfoAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'query' when calling SearchApi->SearchCollections");


            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }

            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CollectionSearchResults>("/search/collections", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchCollections", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search photos Get a single page of photo results for a query. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <returns>PhotoSearchResults</returns>
        public PhotoSearchResults SearchPhotos(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?))
        {
            OASPlash.Core.Client.ApiResponse<PhotoSearchResults> localVarResponse = SearchPhotosWithHttpInfo(query, page, perPage, orderBy, collections, contentFilter, color, orientation);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search photos Get a single page of photo results for a query. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <returns>ApiResponse of PhotoSearchResults</returns>
        public OASPlash.Core.Client.ApiResponse<PhotoSearchResults> SearchPhotosWithHttpInfo(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'query' when calling SearchApi->SearchPhotos");

            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "order_by", orderBy));
            }
            if (collections != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "collections", collections));
            }
            if (contentFilter != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "content_filter", contentFilter));
            }
            if (color != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "color", color));
            }
            if (orientation != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "orientation", orientation));
            }

            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PhotoSearchResults>("/search/photos", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchPhotos", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search photos Get a single page of photo results for a query. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PhotoSearchResults</returns>
        public async System.Threading.Tasks.Task<PhotoSearchResults> SearchPhotosAsync(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OASPlash.Core.Client.ApiResponse<PhotoSearchResults> localVarResponse = await SearchPhotosWithHttpInfoAsync(query, page, perPage, orderBy, collections, contentFilter, color, orientation, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search photos Get a single page of photo results for a query. 
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional; default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="orderBy">How to sort the photos. (Optional; default: relevant). Valid values are latest and relevant.  (optional)</param>
        /// <param name="collections">Collection ID(‘s) to narrow search. Optional. If multiple, comma-separated.  (optional)</param>
        /// <param name="contentFilter">Limit results by content safety. (Optional; default: low). Valid values are low and high.  (optional)</param>
        /// <param name="color">Filter results by color. Optional. Valid values are: black_and_white, black, white, yellow, orange, red, purple, magenta, green, teal, and blue.  (optional)</param>
        /// <param name="orientation">Filter by photo orientation. Optional. (Valid values: landscape, portrait, squarish)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PhotoSearchResults)</returns>
        public async System.Threading.Tasks.Task<OASPlash.Core.Client.ApiResponse<PhotoSearchResults>> SearchPhotosWithHttpInfoAsync(string query, int? page = default(int?), int? perPage = default(int?), OrderBy? orderBy = default(OrderBy?), string collections = default(string), ContentFilter? contentFilter = default(ContentFilter?), Color? color = default(Color?), Orientation? orientation = default(Orientation?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'query' when calling SearchApi->SearchPhotos");


            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "order_by", orderBy));
            }
            if (collections != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "collections", collections));
            }
            if (contentFilter != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "content_filter", contentFilter));
            }
            if (color != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "color", color));
            }
            if (orientation != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "orientation", orientation));
            }

            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PhotoSearchResults>("/search/photos", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchPhotos", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search users Get a single page of user results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>UserSearchResults</returns>
        public UserSearchResults SearchUsers(string query, int? page = default(int?), int? perPage = default(int?))
        {
            OASPlash.Core.Client.ApiResponse<UserSearchResults> localVarResponse = SearchUsersWithHttpInfo(query, page, perPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search users Get a single page of user results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <returns>ApiResponse of UserSearchResults</returns>
        public OASPlash.Core.Client.ApiResponse<UserSearchResults> SearchUsersWithHttpInfo(string query, int? page = default(int?), int? perPage = default(int?))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'query' when calling SearchApi->SearchUsers");

            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }

            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<UserSearchResults>("/search/users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search users Get a single page of user results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserSearchResults</returns>
        public async System.Threading.Tasks.Task<UserSearchResults> SearchUsersAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OASPlash.Core.Client.ApiResponse<UserSearchResults> localVarResponse = await SearchUsersWithHttpInfoAsync(query, page, perPage, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search users Get a single page of user results for a query.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search terms.</param>
        /// <param name="page">Page number to retrieve. (Optional, default: 1)  (optional)</param>
        /// <param name="perPage">Number of items per page. (Optional; default: 10)  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserSearchResults)</returns>
        public async System.Threading.Tasks.Task<OASPlash.Core.Client.ApiResponse<UserSearchResults>> SearchUsersWithHttpInfoAsync(string query, int? page = default(int?), int? perPage = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new OASPlash.Core.Client.ApiException(400, "Missing required parameter 'query' when calling SearchApi->SearchUsers");


            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(OASPlash.Core.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }

            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<UserSearchResults>("/search/users", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SearchUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
