/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using OASPlash.Core.Client;
using OASPlash.Core.Model;

namespace OASPlash.Core.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Month
        /// </summary>
        /// <remarks>
        /// Get the overall Unsplash stats for the past 30 days.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MonthlyStatistics</returns>
        MonthlyStatistics GetMonthlyStatistics();

        /// <summary>
        /// Month
        /// </summary>
        /// <remarks>
        /// Get the overall Unsplash stats for the past 30 days.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MonthlyStatistics</returns>
        ApiResponse<MonthlyStatistics> GetMonthlyStatisticsWithHttpInfo();
        /// <summary>
        /// Totals
        /// </summary>
        /// <remarks>
        /// Get a list of counts for all of Unsplash.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TotalStatistics</returns>
        TotalStatistics GetTotalStatistics();

        /// <summary>
        /// Totals
        /// </summary>
        /// <remarks>
        /// Get a list of counts for all of Unsplash.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TotalStatistics</returns>
        ApiResponse<TotalStatistics> GetTotalStatisticsWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Month
        /// </summary>
        /// <remarks>
        /// Get the overall Unsplash stats for the past 30 days.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MonthlyStatistics</returns>
        System.Threading.Tasks.Task<MonthlyStatistics> GetMonthlyStatisticsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Month
        /// </summary>
        /// <remarks>
        /// Get the overall Unsplash stats for the past 30 days.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MonthlyStatistics)</returns>
        System.Threading.Tasks.Task<ApiResponse<MonthlyStatistics>> GetMonthlyStatisticsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Totals
        /// </summary>
        /// <remarks>
        /// Get a list of counts for all of Unsplash.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TotalStatistics</returns>
        System.Threading.Tasks.Task<TotalStatistics> GetTotalStatisticsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Totals
        /// </summary>
        /// <remarks>
        /// Get a list of counts for all of Unsplash.
        /// </remarks>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TotalStatistics)</returns>
        System.Threading.Tasks.Task<ApiResponse<TotalStatistics>> GetTotalStatisticsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatsApi : IStatsApiSync, IStatsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StatsApi : IDisposable, IStatsApi
    {
        private OASPlash.Core.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public StatsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public StatsApi(string basePath)
        {
            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                new OASPlash.Core.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public StatsApi(OASPlash.Core.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public StatsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public StatsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                new OASPlash.Core.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public StatsApi(HttpClient client, OASPlash.Core.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OASPlash.Core.Client.Configuration.MergeConfigurations(
                OASPlash.Core.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OASPlash.Core.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public StatsApi(OASPlash.Core.Client.ISynchronousClient client, OASPlash.Core.Client.IAsynchronousClient asyncClient, OASPlash.Core.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = OASPlash.Core.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public OASPlash.Core.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public OASPlash.Core.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public OASPlash.Core.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OASPlash.Core.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OASPlash.Core.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Month Get the overall Unsplash stats for the past 30 days.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MonthlyStatistics</returns>
        public MonthlyStatistics GetMonthlyStatistics()
        {
            OASPlash.Core.Client.ApiResponse<MonthlyStatistics> localVarResponse = GetMonthlyStatisticsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Month Get the overall Unsplash stats for the past 30 days.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MonthlyStatistics</returns>
        public OASPlash.Core.Client.ApiResponse<MonthlyStatistics> GetMonthlyStatisticsWithHttpInfo()
        {
            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<MonthlyStatistics>("/stats/month", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMonthlyStatistics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Month Get the overall Unsplash stats for the past 30 days.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MonthlyStatistics</returns>
        public async System.Threading.Tasks.Task<MonthlyStatistics> GetMonthlyStatisticsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OASPlash.Core.Client.ApiResponse<MonthlyStatistics> localVarResponse = await GetMonthlyStatisticsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Month Get the overall Unsplash stats for the past 30 days.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MonthlyStatistics)</returns>
        public async System.Threading.Tasks.Task<OASPlash.Core.Client.ApiResponse<MonthlyStatistics>> GetMonthlyStatisticsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MonthlyStatistics>("/stats/month", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMonthlyStatistics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Totals Get a list of counts for all of Unsplash.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TotalStatistics</returns>
        public TotalStatistics GetTotalStatistics()
        {
            OASPlash.Core.Client.ApiResponse<TotalStatistics> localVarResponse = GetTotalStatisticsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Totals Get a list of counts for all of Unsplash.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TotalStatistics</returns>
        public OASPlash.Core.Client.ApiResponse<TotalStatistics> GetTotalStatisticsWithHttpInfo()
        {
            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TotalStatistics>("/stats/total", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTotalStatistics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Totals Get a list of counts for all of Unsplash.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TotalStatistics</returns>
        public async System.Threading.Tasks.Task<TotalStatistics> GetTotalStatisticsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OASPlash.Core.Client.ApiResponse<TotalStatistics> localVarResponse = await GetTotalStatisticsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Totals Get a list of counts for all of Unsplash.
        /// </summary>
        /// <exception cref="OASPlash.Core.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TotalStatistics)</returns>
        public async System.Threading.Tasks.Task<OASPlash.Core.Client.ApiResponse<TotalStatistics>> GetTotalStatisticsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            OASPlash.Core.Client.RequestOptions localVarRequestOptions = new OASPlash.Core.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OASPlash.Core.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OASPlash.Core.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (publicAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TotalStatistics>("/stats/total", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTotalStatistics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
