// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OASplash.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CollectionLinks
    {
        /// <summary>
        /// Initializes a new instance of the CollectionLinks class.
        /// </summary>
        public CollectionLinks()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CollectionLinks class.
        /// </summary>
        public CollectionLinks(string html = default(string), string photos = default(string), string related = default(string), string self = default(string))
        {
            Html = html;
            Photos = photos;
            Related = related;
            Self = self;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "html")]
        public string Html { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "photos")]
        public string Photos { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "related")]
        public string Related { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "self")]
        public string Self { get; set; }

    }
}
