// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OASplash.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Orientation.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Orientation
    {
        [EnumMember(Value = "landscape")]
        Landscape,
        [EnumMember(Value = "portrait")]
        Portrait,
        [EnumMember(Value = "squarish")]
        Squarish
    }
    internal static class OrientationEnumExtension
    {
        internal static string ToSerializedValue(this Orientation? value)
        {
            return value == null ? null : ((Orientation)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Orientation value)
        {
            switch( value )
            {
                case Orientation.Landscape:
                    return "landscape";
                case Orientation.Portrait:
                    return "portrait";
                case Orientation.Squarish:
                    return "squarish";
            }
            return null;
        }

        internal static Orientation? ParseOrientation(this string value)
        {
            switch( value )
            {
                case "landscape":
                    return Orientation.Landscape;
                case "portrait":
                    return Orientation.Portrait;
                case "squarish":
                    return Orientation.Squarish;
            }
            return null;
        }
    }
}
