// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OASplash.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PortfolioLink
    {
        /// <summary>
        /// Initializes a new instance of the PortfolioLink class.
        /// </summary>
        public PortfolioLink()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PortfolioLink class.
        /// </summary>
        public PortfolioLink(string url = default(string))
        {
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
