/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Exif
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExifTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Exif
        //private Exif instance;

        public ExifTests()
        {
            // TODO uncomment below to create an instance of Exif
            //instance = new Exif();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Exif
        /// </summary>
        [Fact]
        public void ExifInstanceTest()
        {
            // TODO uncomment below to test "IsType" Exif
            //Assert.IsType<Exif>(instance);
        }


        /// <summary>
        /// Test the property 'Make'
        /// </summary>
        [Fact]
        public void MakeTest()
        {
            // TODO unit test for the property 'Make'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'ExposureTime'
        /// </summary>
        [Fact]
        public void ExposureTimeTest()
        {
            // TODO unit test for the property 'ExposureTime'
        }
        /// <summary>
        /// Test the property 'Aperture'
        /// </summary>
        [Fact]
        public void ApertureTest()
        {
            // TODO unit test for the property 'Aperture'
        }
        /// <summary>
        /// Test the property 'FocalLength'
        /// </summary>
        [Fact]
        public void FocalLengthTest()
        {
            // TODO unit test for the property 'FocalLength'
        }
        /// <summary>
        /// Test the property 'Iso'
        /// </summary>
        [Fact]
        public void IsoTest()
        {
            // TODO unit test for the property 'Iso'
        }

    }

}
