/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing OperationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OperationResponse
        //private OperationResponse instance;

        public OperationResponseTests()
        {
            // TODO uncomment below to create an instance of OperationResponse
            //instance = new OperationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperationResponse
        /// </summary>
        [Fact]
        public void OperationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OperationResponse
            //Assert.IsType<OperationResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Photo'
        /// </summary>
        [Fact]
        public void PhotoTest()
        {
            // TODO unit test for the property 'Photo'
        }
        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Fact]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
