/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Orientation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrientationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Orientation
        //private Orientation instance;

        public OrientationTests()
        {
            // TODO uncomment below to create an instance of Orientation
            //instance = new Orientation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Orientation
        /// </summary>
        [Fact]
        public void OrientationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Orientation
            //Assert.IsType<Orientation>(instance);
        }



    }

}
