/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing PhotoStatistics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhotoStatisticsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhotoStatistics
        //private PhotoStatistics instance;

        public PhotoStatisticsTests()
        {
            // TODO uncomment below to create an instance of PhotoStatistics
            //instance = new PhotoStatistics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhotoStatistics
        /// </summary>
        [Fact]
        public void PhotoStatisticsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhotoStatistics
            //Assert.IsType<PhotoStatistics>(instance);
        }


        /// <summary>
        /// Test the property 'Downloads'
        /// </summary>
        [Fact]
        public void DownloadsTest()
        {
            // TODO unit test for the property 'Downloads'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Likes'
        /// </summary>
        [Fact]
        public void LikesTest()
        {
            // TODO unit test for the property 'Likes'
        }
        /// <summary>
        /// Test the property 'Views'
        /// </summary>
        [Fact]
        public void ViewsTest()
        {
            // TODO unit test for the property 'Views'
        }

    }

}
