/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing PhotoStatisticsDownloads
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhotoStatisticsDownloadsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhotoStatisticsDownloads
        //private PhotoStatisticsDownloads instance;

        public PhotoStatisticsDownloadsTests()
        {
            // TODO uncomment below to create an instance of PhotoStatisticsDownloads
            //instance = new PhotoStatisticsDownloads();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhotoStatisticsDownloads
        /// </summary>
        [Fact]
        public void PhotoStatisticsDownloadsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhotoStatisticsDownloads
            //Assert.IsType<PhotoStatisticsDownloads>(instance);
        }


        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Historical'
        /// </summary>
        [Fact]
        public void HistoricalTest()
        {
            // TODO unit test for the property 'Historical'
        }

    }

}
