/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Topic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TopicTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Topic
        //private Topic instance;

        public TopicTests()
        {
            // TODO uncomment below to create an instance of Topic
            //instance = new Topic();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Topic
        /// </summary>
        [Fact]
        public void TopicInstanceTest()
        {
            // TODO uncomment below to test "IsType" Topic
            //Assert.IsType<Topic>(instance);
        }


        /// <summary>
        /// Test the property 'ConverPhoto'
        /// </summary>
        [Fact]
        public void ConverPhotoTest()
        {
            // TODO unit test for the property 'ConverPhoto'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EndsAt'
        /// </summary>
        [Fact]
        public void EndsAtTest()
        {
            // TODO unit test for the property 'EndsAt'
        }
        /// <summary>
        /// Test the property 'Featured'
        /// </summary>
        [Fact]
        public void FeaturedTest()
        {
            // TODO unit test for the property 'Featured'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'OnlySubmissionsAfter'
        /// </summary>
        [Fact]
        public void OnlySubmissionsAfterTest()
        {
            // TODO unit test for the property 'OnlySubmissionsAfter'
        }
        /// <summary>
        /// Test the property 'Owners'
        /// </summary>
        [Fact]
        public void OwnersTest()
        {
            // TODO unit test for the property 'Owners'
        }
        /// <summary>
        /// Test the property 'PublishedAt'
        /// </summary>
        [Fact]
        public void PublishedAtTest()
        {
            // TODO unit test for the property 'PublishedAt'
        }
        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'StartsAt'
        /// </summary>
        [Fact]
        public void StartsAtTest()
        {
            // TODO unit test for the property 'StartsAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'TopContributors'
        /// </summary>
        [Fact]
        public void TopContributorsTest()
        {
            // TODO unit test for the property 'TopContributors'
        }
        /// <summary>
        /// Test the property 'TotalPhotos'
        /// </summary>
        [Fact]
        public void TotalPhotosTest()
        {
            // TODO unit test for the property 'TotalPhotos'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
