/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing TopicLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TopicLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TopicLinks
        //private TopicLinks instance;

        public TopicLinksTests()
        {
            // TODO uncomment below to create an instance of TopicLinks
            //instance = new TopicLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TopicLinks
        /// </summary>
        [Fact]
        public void TopicLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" TopicLinks
            //Assert.IsType<TopicLinks>(instance);
        }


        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Photos'
        /// </summary>
        [Fact]
        public void PhotosTest()
        {
            // TODO unit test for the property 'Photos'
        }
        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Fact]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }

    }

}
