/*
 * Unsplash API
 *
 * This document describes the resources that make up the official Unsplash JSON API. 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OASPlash.Core.Api;
using OASPlash.Core.Model;
using OASPlash.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OASPlash.Core.Test.Model
{
    /// <summary>
    ///  Class for testing UserSearchResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserSearchResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserSearchResults
        //private UserSearchResults instance;

        public UserSearchResultsTests()
        {
            // TODO uncomment below to create an instance of UserSearchResults
            //instance = new UserSearchResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserSearchResults
        /// </summary>
        [Fact]
        public void UserSearchResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserSearchResults
            //Assert.IsType<UserSearchResults>(instance);
        }


        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
